name: draggable
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  auto_route: ^5.0.4
  bloc: ^8.1.0
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  #flutter_custom_clippers: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  rename: ^2.0.1
  share_plus: ^6.3.0
  velocity_x: ^3.6.0

dev_dependencies:
  auto_route_generator:
  bloc_test:
  build_runner:
  flutter_test:
    sdk: flutter
  mocktail:
  very_good_analysis:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/.
